config/routes.rb
DeviseExample::Application.routes.draw do

  devise_for :users, :admins

  get '/token' => 'home#token', as: :token

  resources :home, only: :index
  resources :admins, only: :index

  root 'home#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable, :confirmable, :lockable

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_admin!

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit! }
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: :token

  def token
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
  def title(page_title, show_title = true)
    @content_for_title = page_title.to_s
    @show_title = show_title
  end

  def show_title?
    @show_title
  end
end

app/views/admins/index.html.erb
<% title 'Admin' -%>

<p>Welcome to Admin Section.</p>

app/views/home/index.html.erb
<h1>Hello!</h1>

<% unless admin_signed_in? -%>
  <p><%= link_to 'Sign up as Admin', new_admin_registration_path %></p>
  <p><%= link_to 'Sign in as Admin', new_admin_session_path %></p>
<% end -%>

<% unless user_signed_in? -%>
  <p><%= link_to 'Sign up as User', new_user_registration_path %></p>
  <p><%= link_to 'Sign in as User', new_user_session_path %></p>
<% end -%>

<% if user_signed_in? -%>
  <p><%= link_to 'Token Authentication Example', token_path(auth_token: current_user.authentication_token) %></p>
<% end -%>

<p>Hello World!</p>

app/views/home/token.html.erb
<h1>Hello, <%= current_user.email %></h1>

<p>This link (with the auth_token param) will work even if you're not signed in.</p>

<p>Save this link, sign out, and try it!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title><%= h(yield(:title) || "Devise") %></title>
    <%= csrf_meta_tag %>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag :application %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg, id: "flash_#{name}" if msg.is_a?(String) %>
      <%- end -%>

      <p><%= link_to 'Home', root_path %></p>

      <% if user_signed_in? -%>
        <div id="user_login_box" style="float:right">
          <%= current_user.email %> |
          <%= link_to 'My info', edit_user_registration_path %> |
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
        </div>
      <% end -%>
      <% if admin_signed_in? -%>
        <div id="admin_login_box" style="float:left">
          <%= current_admin.email %> |
          <%= link_to 'Admin section', admins_path %> |
          <%= link_to 'Sign out', destroy_admin_session_path, method: :delete %>
        </div>
      <% end -%>
      <div style="clear:both"></div>

      <%- if show_title? -%>
        <h1><%=h yield(:title) %></h1>
      <%- end -%>

      <%= yield %>
    </div>
  </body>
</html>